on:
  push:
    branches:
      - feature/add-macos-arm64

name: testMacos
jobs:
  macosarm64:
    name: 'MacOS (arm64)'
    runs-on: macos-11

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: ./install.dependencies.sh
        working-directory: build/macos-arm64

      - name: Clone ImageMagick libraries
        run: ./checkout.sh macos ../../../artifacts
        working-directory: src/ImageMagick

      - name: Build libraries
        run: ../../../build/macos-arm64/build.libraries.sh ../../../build/libraries
        working-directory: src/ImageMagick/libraries

      - name: Build ImageMagick
        run: ../../../build/shared/build.ImageMagick.sh macos arm64
        working-directory: src/ImageMagick/libraries

      - name: Build Native
        run: ../../build/shared/build.Native.sh macos arm64
        working-directory: src/Magick.Native

      - name: Copy Native
        run: ../../build/shared/copy.Native.sh macos arm64 ../../artifacts
        working-directory: src/Magick.Native

      - name: Upload library
        uses: actions/upload-artifact@v3
        with:
          name: macos
          path: artifacts
